[package]
name = "shrev"
version = "0.6.0"
authors = ["Simon Rönnberg <simon.ronnberg@codemill.se>"]
repository = "https://github.com/Rhuagh/shrev-rs.git"
homepage = "https://github.com/Rhuagh/shrev-rs.git"

license = "MIT/Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/shrev"
description = "Event channel, meant to be used with `specs`."

keywords = ["specs", "events"]

[dependencies]
